# Generated by Django 4.2.17 on 2024-12-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_location_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='location',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
