# Generated by Django 4.2.17 on 2024-12-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_created_location_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('lat', 'lng')},
        ),
    ]
